[[in]]
name = "file"
type = "file"

[[nodes]]
id = "read"
function = "read_file"
parameters = [ { key = "in.file" } ]

[[nodes]]
id = "upper"
function = "uppercase"
parameters = [ { key = "read.text" } ]

[[nodes]]
id = "lower"
function = "lowercase"
parameters = [ { key = "read.text" } ]

[[nodes]]
id = "concat"
function = "concat"
parameters = [ { key = "upper.result" }, { key = "lower.result" } ]

[[nodes]]
id = "parse"
function = "parse_markdown"
parameters = [ { key = "concat.result" } ]

[[nodes]]
id = "render"
function = "render_html5"
parameters = [ { key = "parse.result" } ]

[[nodes]]
id = "new_path"
function = "change_extension"
parameters = [ { text = "html" }, { key = "read.path" } ]

[[nodes]]
id = "output"
function = "make_file"
parameters = [ { key = "new_path.result" }, { key = "render.result" } ]

[[out]]
name = "output_path"
key = "new_path.result"

[[out]]
name = "file"
key = "output.result"
