[[in]]
name = "path"
type = "path"

[[nodes]]
id = "read"
type = { function = "file_contents" }
parameters = [ { name = "path", key = "in.path" } ]

[[nodes]]
id = "upper"
type = { function = "uppercase" }
parameters = [ { name = "text", key = "read.result" } ]

[[nodes]]
id = "lower"
type = { function = "lowercase" }
parameters = [ { name = "text", key = "read.result" } ]

[[nodes]]
id = "concat"
type = { function = "concat" }
parameters = [ { name = "a", key = "upper.result" }, { name = "b", key = "lower.result" } ]

[[nodes]]
id = "parse"
type = { function = "parse_markdown" }
parameters = [ { name = "text", key = "concat.result" } ]

[[nodes]]
id = "render"
type = { function = "render_html5" }
parameters = [ { name = "pandoc", key = "parse.result" } ]

[[nodes]]
id = "new_path"
type = { function = "change_extension" }
parameters = [ { name = "extension", text = "html" }, { name="path", key = "in.path" } ]

[[nodes]]
id = "output"
type = { function = "make_file" }
parameters = [ { name = "path", key = "new_path.result" }, { name = "text", key = "render.result" } ]

[[out]]
name = "file"
key = "output.result"

[[out]]
name = "path"
key = "new_path.result"

[[out]]
name = "text"
key = "render.result"